apiVersion: v1
kind: Config
clusters:
- name: "swe645hw3"
  cluster:
    server: "https://3.225.247.36/k8s/clusters/c-m-hdr7tnwg"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN4TWpnMApNVEl3TWpBZUZ3MHlOREEwTVRFeE16RXpNakphRncwek5EQTBNRGt4TXpFek1qSmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56RXlPRFF4TWpBeU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRVFGZ0ErRVlqd3lKZwpScUQ4QW9jN3I1UzNvZmRDNGtwWnZEY3NVW\
      nZnRnVpTnB3YitRdndSSU9yUUN6SHdpcmFSNWRaSFU2WnZMbWRBCkt1S3AzN0Fab2FOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      3A1QTlLRThwdnhETURTV0QrNE16bVZmZmZBTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUNkYgo4b\
      3RWT1NwNm1EbzdaazExQWNoTXQzYlJ1dm5pQmJYbVE3bGxDYVIyQWlFQWprc3hLM2xHNDBVT3JuZ\
      zNlMFNHCnhqeFEwWGo4N1FBcktIWkdKTy9Fc0FBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe645hw3"
  user:
    token: "kubeconfig-user-lcpg2g5cwq:fn6pmpv4j26f2p7tj9pxskjcnkkcj5xgszhc47gjjvwpspsrc7h4f2"


contexts:
- name: "swe645hw3"
  context:
    user: "swe645hw3"
    cluster: "swe645hw3"

current-context: "swe645hw3"
